import Head from "next/head";
import Image from "next/image";
import calculatorIcon from "public/images/icon-calculator.svg";
import karmaIcon from "public/images/icon-karma.svg";
import supervisorIcon from "public/images/icon-supervisor.svg";
import teamIcon from "public/images/icon-team-builder.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/favicon-32x32.png" />
      </Head>
      <main className="font-Poppins h-full bg-[#FAFAFA] text-[#4C4E61] px-[20px] xl:px-[165px] flex items-center justify-center">
        <div className="xl:h-full xl:flex xl:flex-col xl:items-center xl:justify-center">
          <div className="flex flex-col xl:items-center xl:w-[510px]">
            <h1 className=" text-[26px] flex justify-between tracking-[0.035rem] font-extralight">
              Reliable, efficient delivery
            </h1>
            <p className="  font-semibold flex justify-between text-[26px] tracking-[0.05rem]">
              Powered by Technology
            </p>
            <p className="text-[#A3A5AE] text-center mt-[15px] tracking-[0.04rem] xl:tracking-normal">
              Our Artificial Intelligence powered tools use millions of project
              data points to ensure that your project is successful
            </p>
          </div>
          <div className="flex flex-col gap-[25px] mt-[70px] xl:flex-row xl:items-center">
            <div className="flex flex-col shadow-personal  xl:h-[250px] xl:w-[350px] bg-[#FFF] border-t-4 border-[#45D3D3] rounded-lg p-[28px]">
              <h2 className="font-semibold text-lg">Supervisor</h2>
              <p className="text-sm mt-[5px] text-[#A3A5AE]">
                Monitors activity to identify project roadblocks
              </p>
              <Image
                src={supervisorIcon}
                alt="supervisorIco"
                className="place-self-end mt-[30px]"
              ></Image>
            </div>
            <div className="flex flex-col gap-[25px]">
              <div className="flex flex-col shadow-personal xl:h-[250px] xl:w-[350px] bg-[#FFF] border-t-4 border-[#EA5353] rounded-lg p-[28px]">
                <h2 className="font-semibold text-lg">Team Builder</h2>
                <p className="text-sm mt-[5px] text-[#A3A5AE]">
                  Scans our talent network to create the optimal team for your
                  project
                </p>
                <Image
                  src={teamIcon}
                  alt="supervisorIco"
                  className="place-self-end mt-[30px]"
                ></Image>
              </div>
              <div className="flex flex-col shadow-personal xl:h-[250px] xl:w-[350px] bg-[#FFF] border-t-4 border-[#FCAF4A] rounded-lg p-[28px]">
                <h2 className="font-semibold text-lg">Karma</h2>
                <p className="text-sm mt-[5px] text-[#A3A5AE]">
                  Regularly evaluates our talent to ensure quality
                </p>
                <Image
                  src={karmaIcon}
                  alt="supervisorIco"
                  className="place-self-end mt-[30px]"
                ></Image>
              </div>
            </div>
            <div className="flex flex-col shadow-personal xl:h-[250px] xl:w-[350px] bg-[#FFF] border-t-4 border-[#549EF2] rounded-lg p-[28px]">
              <h2 className="font-semibold text-lg">Calculator</h2>
              <p className="text-sm mt-[5px] text-[#A3A5AE]">
                Uses data from past projects to provide better delivery
                estimates
              </p>
              <Image
                src={calculatorIcon}
                alt="supervisorIco"
                className="place-self-end mt-[30px]"
              ></Image>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
